### ISSUE TITLE
Wrong node version

### ISSUE THREAD

**Issue by serut** [freesoftwareneedsfreetools/bugreport001#1]
You use the `6.3.0` version of node, which is completly not supported by meteor 1.3
Also, you should add a CI test that shows the error

**Comment by freesoftwareneedsfreetools** [comment]
Please let me know if commit 7352c73899e01518aae6ab5d7800ec36140b3d99 doesn't address your concerns.

Thanks in advance!

**Comment by serut** [comment]
Yeah it's perfect.

> I made a modification of flow router which raises `There is no route for the path: /local` as a log when testing and not as an error, and basically it works  

Check this out https://github.com/noahsw/todos using https://github.com/serut/flow-router

But your original issue is not with the meteor build version ?

**Comment by freesoftwareneedsfreetools** [comment]
Originally I ran into trouble when trying to set up spacejam a bit over a month ago.

FWIW I asked about it in the forum, but didn't have much luck, could not make it work...
https://forums.meteor.com/t/spacejam-phantomjs-no-route-for-the-path-local-flowrouter/25233

Thanks for the patched version of flowrouter. I will give it a try!
